- platform: nest
  monitored_conditions:
    - 'temperature'
    - 'target'
    - 'humidity'
    - 'operation_mode'
    - 'last_connection'
    - 'battery_level'
    - 'weather_condition'
    - 'weather_temperature'
    - 'wind_speed'
    - 'wind_direction'
    # - 'co_status' # Nest Protect only
    # - 'smoke_status' # Nest Protect only

# - platform: template
#   sensors:
#      nest_away_mode:
#        entity_id: climate.living_roomwoonkamer
#        value_template: "{{ is_state_attr('climate.living_roomwoonkamer', 'away_mode', 'on') }}"
